# Generated by Django 3.2.4 on 2021-06-06 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterfacesModel',
            fields=[
                ('id', models.IntegerField(help_text='主键', primary_key=True, serialize=False, unique=True, verbose_name='主键')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('desc', models.TextField(default='', help_text='注释', verbose_name='注释')),
                ('name', models.CharField(help_text='名称', max_length=20, unique=True, verbose_name='名称')),
                ('tester', models.CharField(help_text='项目测试人员', max_length=10, verbose_name='项目测试人员')),
                ('project', models.ForeignKey(help_text='外键_项目id', on_delete=django.db.models.deletion.CASCADE, related_name='project_link_Interface', to='projects.projectsmodel', verbose_name='外键_项目id')),
            ],
            options={
                'db_table': 'tb_interfaces',
                'ordering': ['id'],
            },
        ),
    ]
