# Generated by Django 3.2.1 on 2021-06-09 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsmodel',
            name='id',
            field=models.AutoField(help_text='主键', primary_key=True, serialize=False, verbose_name='主键'),
        ),
    ]
